name: Build App

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: build-push
          uses: docker/build-push-action@v1
          with:
            username: julienlm2
            password: dckr_pat_Snq3O5s3k_-LSu0_4TtjCkYm4xQ
            registry: docker.io
            repository: julienlm2/cd
            tag_with_sha: true
