name: Build App

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: build-push
          uses: docker/build-push-action@v1
          with:
            username: julienlm2
            password: dckr_pat_Snq3O5s3k_-LSu0_4TtjCkYm4xQ
            registry: docker.io
            repository: julienlm2/cd
            tag_with_sha: true
    sonarcloud:
        name: SonarCloud
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          - name: SonarCloud Scan
            uses: SonarSource/sonarcloud-github-action@master
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

